ajax/urls.py
from django.conf.urls import patterns, url
import views
urlpatterns = patterns(
    '',
    url(r'^top-travels/(\d+)$', views.TopTravelsView.as_view()),
    url(r'^top-travel-friends/(\d+)$', views.TopTravelFriendsView.as_view()),
    url(r'^furthest-friends/(\d+)$', views.FurthestFriendsView.as_view()),
    url(r'^progress/(\d+)/$', views.ProgressView.as_view()),
)

falcon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from fb import views as fbViews
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^connect/$', fbViews.ConnectView.as_view()),
    url(r'^create/(\d+)$', fbViews.CreateView.as_view()),
    url(r'^report/(\d+)$', fbViews.ReportView.as_view()),
    url(r'^facebook/(\d+)$', fbViews.IndexView.as_view()),
    url(r'^facebook$', fbViews.IndexView.as_view()),
    url(r'^ajax/', include('ajax.urls')),
    url(r'^admin/', include(admin.site.urls))
)

fb/models.py
from django.db import models
from datetime import date


# Person
class Person(models.Model):

    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('X', 'Unknown'),
    ]

    RELATIONSHIP_CHOICES = [
        ('S', 'Single'),
        ('R', 'In a relationship'),
        ('E', 'Engaged'),
        ('M', 'Married'),
        ('C', 'Its complicated'),
        ('O', 'In an open relationship'),
        ('W', 'Widowed'),
        ('Q', 'Separated'),
        ('D', 'Divorced'),
        ('U', 'In a civil union'),
        ('P', 'In a domestic partnership'),
        ('X', 'Unknown'),
    ]

    fb_id = models.CharField(max_length=191, null=True, blank=True)
    relationships = models.ManyToManyField(
        'self', through='Relationship', symmetrical=False,
        related_name='related_to+'
    )
    access_token = models.TextField(null=True, blank=True)
    hash = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    middle_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    birthday = models.DateField(null=True, blank=True)
    relationship_status = models.CharField(
        max_length=1, choices=RELATIONSHIP_CHOICES
    )
    significant_other = models.CharField(max_length=30, null=True, blank=True)

    @property
    def name(self):
        name = self.first_name
        if self.middle_name is not '':
            name += ' ' + self.middle_name
        name += self.last_name
        return name

    @property
    def friends(self):
        return self.relationships.all()

    @property
    def posts(self):
        try:
            return Post.objects.filter(person=self)
        except Post.DoesNotExist:
            return None

    @property
    def hometown(self):
        try:
            return Location.objects.get(person=self, type='H')
        except Location.DoesNotExist:
            return None

    @property
    def locations(self):
        try:
            return Location.objects.filter(person=self)
        except Location.DoesNotExist:
            return None

    @property
    def progress(self):
        try:
            return Progress.objects.filter(person=self)
        except Progress.DoesNotExist:
            return None

    @property
    def friends_travels(self):
        locations = Location.objects.filter(
            person_id__in=self.friends,
            travel_distance__isnull=False,
            type='P'
        )
        return locations

    @property
    def age(self):
        today = date.today()
        try:
            birthday = self.birthday.replace(year=today.year)
        except ValueError:
            # raised when birth date is February 29 and the current year is not
            # a leap year
            birthday = self.birthday.replace(
                year=today.year,
                day=self.birthday.day-1
            )
        if birthday > today:
            return today.year - self.birthday.year - 1
        else:
            return today.year - self.birthday.year

    @property
    def friends_hometowns(self):
        """
        Returns a list of Locations for the hometowns of all Persons befriended
        with the current Person
        """
        locations = Location.objects.filter(
            person_id__in=self.friends,
            hometown_distance__isnull=False,
            type='H'
        )
        return locations

    @property
    def male_friends(self):
        """
        Returns a list of Persons who are male and befriended with the current
        Person
        """
        return self.friends.filter(gender='M')

    @property
    def male_friends_percentage(self):
        """
        Calculates the percentage of male friends relatively to the total
        amount of friends
        """
        number_of_male_friends = float(len(self.male_friends))
        number_of_friends = float(len(self.friends))
        percentage = (number_of_male_friends / number_of_friends) * 100
        return percentage

    @property
    def female_friends(self):
        """
        Returns a list of persons who are female and befriended with the current
        Person
        """
        return self.friends.filter(gender='F')

    @property
    def female_friends_percentage(self):
        """
        Calculates the percentage of female friends relatively to the total
        amount of friends
        """
        number_of_female_friends = float(len(self.female_friends))
        number_of_friends = float(len(self.friends))
        return number_of_female_friends / number_of_friends * 100

    def friends_by_mutual_friends(self, gender=None, order='ASC', limit=None):
        """
        Selects all friends by mutual friend count. It is possible to select by
        gender. Ordering allows selection of least mutual friends (ASC) or most
        mutual friends (DESC)
        """
        sql = """
            SELECT *
            FROM `fb_person`
               LEFT JOIN `fb_relationship`
                   ON ( `fb_person`.`id` = `fb_relationship`.`to_person_id` )
            WHERE  `fb_relationship`.`from_person_id` = %s
            """ % self.id
        if gender is not None:
            sql += """
                AND `fb_person`.`gender` = "%s"
                """ % gender
        sql += """
            ORDER  BY `fb_relationship`.`mutual_friend_count` %s
            """ % order
        if limit is not None:
            sql += """
                LIMIT %s
                """ % limit
        friends = Person.objects.raw(sql)
        return friends

    def mutual_friends_percentage(self, person):
        """
        Calculates the percentage of friends you have in common with a given
        person
        """
        mutual_friends = float(len(self.mutual_friends(person)))
        friends = float(len(self.friends()))
        return mutual_friends / friends * 100

    def friends_by_like_average(self, gender=None, order='ASC', limit=None):
        """
        Selects all friends and calculates the average like count for each
        friend. It is possible to select by gender. Ordering allows selection
        of lowest average like count (ASC) or highest average like count (DESC)
        """
        sql = """
            SELECT *, AVG(`like_count`) AS average
            FROM `fb_person`
                LEFT JOIN `fb_post` as a
                    ON ( `fb_person`.`id` = a.`person_id` )
                LEFT JOIN `fb_relationship`
                    ON ( `fb_person`.`id` = `fb_relationship`.`to_person_id` )
            WHERE `fb_relationship`.`from_person_id` = %s
            """ % self.id
        if gender is not None:
            sql += """
                AND `fb_person`.`gender` = "%s"
                """ % gender
        sql += """
            AND a.`like_count` IS NOT NULL
            GROUP BY `fb_person`.`id`
            ORDER BY average %s
        """ % order
        if limit is not None:
            sql += """
                LIMIT %s
                """ % limit

        friends = Person.objects.raw(sql)
        return friends

    def friends_by_post_count(self, gender=None, order='ASC', limit=None):
        """
        Selects all friends and calculates the number of posts for each
        friend. It is possible to select by gender. Ordering allows selection
        of least amount of posts (ASC) or most amount of posts (DESC)
        """
        sql = """
            SELECT *, COUNT(`like_count`) AS total
            FROM `fb_person`
                LEFT JOIN `fb_post` as a
                    ON ( `fb_person`.`id` = a.`person_id` )
                LEFT JOIN `fb_relationship`
                    ON ( `fb_person`.`id` = `fb_relationship`.`to_person_id` )
            WHERE `fb_relationship`.`from_person_id` = %s
            """ % self.id
        if gender is not None:
            sql += """
                AND `fb_person`.`gender` = "%s"
                """ % gender
        sql += """
            GROUP BY `fb_person`.`id`
            ORDER BY total %s
        """ % order
        if limit is not None:
            sql += """
                LIMIT %s
                """ % limit

        friends = Person.objects.raw(sql)
        return friends

    def add_relationship(self, person):
        """
        Creates a Relationship object linking the current person and a given
        person
        """
        relationship, created = Relationship.objects.get_or_create(
            from_person=person, to_person=self
        )
        return relationship

    def remove_relationship(self, person):
        """
        Removes the Relationship object linking the current person and a given
        person
        """
        Relationship.objects.filter(from_person=self, to_person=person).delete()


# Relationship
class Relationship(models.Model):
    from_person = models.ForeignKey(Person, related_name='from_people')
    to_person = models.ForeignKey(Person, related_name='to_people')
    mutual_friend_count = models.IntegerField(max_length=30, null=True, blank=True)


# Location
class Location(models.Model):

    LOCATION_TYPES = [
        ('H', 'Hometown'),
        ('C', 'Current location'),
        ('P', 'Photo'),
        ('A', 'Album'),
    ]

    person = models.ForeignKey('Person')
    fb_id = models.CharField(max_length=191, null=True, blank=True)
    name = models.TextField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    postal_code = models.CharField(max_length=191, null=True, blank=True)
    city = models.CharField(max_length=191, null=True, blank=True)
    country = models.CharField(max_length=191, null=True, blank=True)
    travel_distance = models.FloatField(null=True, blank=True)
    hometown_distance = models.FloatField(null=True, blank=True)

fb/views/connectView.py
from django.views.generic.base import View
from django.shortcuts import redirect
from django.http import HttpResponse
from fb.facebook import Auth, Api
from fb.models import Person
from fb.storage import Store


class ConnectView(View):

    person = None
    access_token = None

    def get(self, request, *args, **kwargs):

        """
        If an access_code has been given, we should make a request to get the access_token from it. If no access_code
        was given, we should first ask for one
        """
        auth = Auth()

        # Check if a code had been provided in the request
        if 'code' in request.GET:

            # Request and validate an access_token for a given access_code
            code = request.GET['code']
            access_token = auth.get_access_token(code)
            if auth.validate_access_token(access_token) is True:
                fb_id = auth.get_user_id(access_token)
                self.access_token = access_token
                self.create_person(fb_id)

                # Redirect the user to notify if all went well
                return redirect('/facebook/' + str(self.person.pk))

            # Something went wrong message
            else:
                return HttpResponse('Something went wrong will validating the facebook access_token')

        # Request an access code
        else:
            url = auth.get_access_url()
            return redirect(url)

    def create_person(self, fb_id):
        try:
            self.person = Person.objects.get(fb_id=fb_id)
        except Person.DoesNotExist:
            self.person = Person.objects.create(fb_id=fb_id)
        self.person.access_token = self.access_token
        self.person.save()
        self.fetch_data(fb_id)

    def fetch_data(self, fb_id):
        api = Api(self.person.access_token)
        request = {
            'id': self.person.fb_id,
            'request': str(self.person.fb_id)
        }
        generator = api.request([request])
        for responses in generator:
            for response in responses:
                store = Store()
                self.person = store.user(response, self.person)

fb/views/indexView.py
from django.views.generic.base import View
from django.shortcuts import render, redirect
from fb.models import Person


class IndexView(View):

    def get(self, request, id=None):

        """
        The access_code for API calls is stored in the Person database. If no person could be found we should we should
        first obtain the access_code via the connect view.
        """
        try:
            person = Person.objects.get(pk=id)
        except Person.DoesNotExist:
            return redirect('/connect')

        # Check if the access token has been set
        if person.access_token is None:
            return redirect('/connect')

        return render(
            request,
            'index.html',
            {
                'person': person
            }
        )

fb/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Hi, {{ person.first_name }}</h1>

    <h2>What do you want to do?</h2>

    <a href="/create/{{ person.id }}" class="btn btn-lg btn-default btn-primary">Create report</a>
    <a href="/report/{{ person.id }}" class="btn btn-lg btn-default">Show report</a>

{% endblock %}

fb/templates/report.html
{% extends "base.html" %}

{% block content %}

    {% load staticfiles %}

    {# General #}
    <div class="page-header text-center">
        <h2>General info</h2>
    </div>
    <div class="row">
        <div id="person" class="col-6" data-id="{{ person.id }}">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Identity card</span>
                </div>
                <div class="box-content">
                    <img src="https://graph.facebook.com/{{ person.fb_id }}/picture?width=80&height=97" alt="{{ person.name }}" height="97">
                    <div class="box-col-1">
                        <ul>
                            <li><strong>Name:</strong> {{ person.name }}</li>
                            <li><strong>Gender:</strong> {{ person.get_gender_display }}</li>
                            <li><strong>Birthday:</strong> {{ person.birthday }}</li>
                            <li><strong>Friends:</strong> {{ friends }}</li>
                            <li><strong>Status:</strong> {{ person.get_relationship_status_display }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
         <div class="col-6">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Friends</span>
                </div>
                <div class="box-content">
                    <div class="box-col-2">
                        <img src="{% static "img/male.jpg" %}" alt="My image"/><br>
                        <span class="large-text">{{ person.male_friends_percentage|floatformat:0 }}%</span><br>
                        <span class="small-text">({{ person.male_friends|length }}/{{ person.friends|length }})</span>
                    </div>
                    <div class="box-col-2">
                        <img src="{% static "img/female.jpg" %}" alt="My image"/><br>
                        <span class="large-text">{{ person.female_friends_percentage|floatformat:0 }}%</span><br>
                        <span class="small-text">({{ person.female_friends|length }}/{{ person.friends|length }})</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

   {# Demographics #}
    <div class="page-header text-center">
        <h2>Demographics</h2>
    </div>
    <div class="row">
         <div class="col-12 text-center">
            <div id="report-demographics-buttons" class="btn-group">
                <button data-url="percentages" type="button" class="btn btn-default active">Percentages</button>
                <button data-url="totals" type="button" class="btn btn-default">Totals</button>
            </div>
        </div>
        <div class="col-12">
            <div id="demographics-chart"></div>
            <script>
                var reportMaleAges = [];
                var reportFemaleAges = [];
                {% for male_age in male_ages %}
                    reportMaleAges.push({{ male_age }})
                {% endfor %}
                {% for female_age in female_ages %}
                    reportFemaleAges.push({{ female_age }})
                {% endfor %}
            </script>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Youngest</span>
                </div>
                <div class="box-content">
                    <div class="box-col-2 box-blue">
                        <span class="large-text">{{ youngest_male.age }}</span><br>
                        <span class="small-text">({{ youngest_male.name|truncatechars:25 }})</span>
                    </div>
                    <div class="box-col-2 box-pink">
                        <span class="large-text">{{ youngest_female.age }}</span><br>
                        <span class="small-text">({{ youngest_female.name|truncatechars:25 }})</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Average</span>
                </div>
                <div class="box-content">
                    <div class="box-col-2 box-blue">
                        <span class="large-text">{{ average_male_age }}</span><br>
                        <span class="small-text">({{ person.male_friends|length }} males)</span>
                    </div>
                    <div class="box-col-2 box-pink">
                        <span class="large-text">{{ average_female_age }}</span><br>
                        <span class="small-text">({{ person.female_friends|length }} females)</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Oldest</span>
                </div>
                <div class="box-content">
                    <div class="box-col-2 box-blue">
                        <span class="large-text">{{ oldest_male.age }}</span><br>
                        <span class="small-text">({{ oldest_male.name|truncatechars:25 }})</span>
                    </div>
                    <div class="box-col-2 box-pink">
                        <span class="large-text">{{ oldest_female.age }}</span><br>
                        <span class="small-text">({{ oldest_female.name|truncatechars:25 }})</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {# Age #}
    <div class="page-header text-center">
        <h2>Age</h2>
    </div>
    <div class="row">
        <div class="col-6">
            <h3>Youngest</h3>
            <ol>
            {% for friend in youngest_friends %}
                <li>
                    <img src="https://graph.facebook.com/{{ friend.fb_id }}/picture" width="30">
                    {{ friend.first_name }} {{ friend.last_name }} ({{ friend.age }} years)
                </li>
            {% endfor %}
            </ol>
        </div>
        <div class="col-6">
            <h3>Oldest</h3>
            <ol>
            {% for friend in oldest_friends %}
                <li>
                    <img src="https://graph.facebook.com/{{ friend.fb_id }}/picture" width="30">
                    {{ friend.first_name }} {{ friend.last_name }} ({{ friend.age }} years)
                </li>
            {% endfor %}
            </ol>
        </div>
    </div>

    {# Mutual friends #}
    <div class="page-header text-center">
        <h2>Mutual Friends</h2>
    </div>
    <div class="row">
         <div class="col-12">
            <div id="connections-chart"></div>
            <script>
                var reportMaleConnections = [];
                var reportFemaleConnections = [];
                {% for male_connection in male_connections %}
                    reportMaleConnections.push("{{ male_connection }}")
                {% endfor %}
                {% for female_connection in female_connections %}
                    reportFemaleConnections.push("{{ female_connection }}")
                {% endfor %}
            </script>
        </div>
        <div class="col-6">
            <h3>Most mutual friends</h3>
            <ol>
                {% for friend in top_connected_friends %}
                    <li>
                        <img src="https://graph.facebook.com/{{ friend.fb_id }}/picture" width="30">
                        {{ friend.first_name }} {{ friend.last_name }} ({{ friend.mutual_friend_count }} mutual friends)
                    </li>
                {% endfor %}
            </ol>
        </div>
        <div class="col-6">
            <h3>Least mutual friends</h3>
            <ol>
                {% for friend in least_connected_friends %}
                    <li>
                        <img src="https://graph.facebook.com/{{ friend.fb_id }}/picture" width="30">
                        {{ friend.first_name }} {{ friend.last_name }} ({{ friend.mutual_friend_count }} mutual friends)
                    </li>
                {% endfor %}
            </ol>
        </div>
    </div>

   {# Relationships #}
    <div class="page-header text-center">
        <h2>Relationships</h2>
    </div>
    <div class="row">
         <div class="col-12 text-center">
            <div id="report-relationship-buttons" class="btn-group">
                <button data-url="percentages" type="button" class="btn btn-default active">Percentages</button>
                <button data-url="totals" type="button" class="btn btn-default">Totals</button>
            </div>
        </div>
        <div class="col-12">
            <div id="relationships-chart"></div>
            <script>
                var reportMaleRelationships = [];
                var reportFemaleRelationships = [];
                {% for male_relationship in male_relationships %}
                    reportMaleRelationships.push("{{ male_relationship }}")
                {% endfor %}
                {% for female_relationship in female_relationships %}
                    reportFemaleRelationships.push("{{ female_relationship }}")
                {% endfor %}
            </script>
        </div>
    </div>

    {# Locations #}
    <div class="page-header text-center">
        <h2>Locations</h2>
    </div>
    <div id="report-locations" class="row">
        <div class="col-12 text-center">
            <div id="report-locations-buttons" class="btn-group">
                <button data-url="top-travels" type="button" class="btn btn-default active">Your travels</button>
                <button data-url="furthest-friends" type="button" class="btn btn-default">Furthest hometowns</button>
                <button data-url="top-travel-friends" type="button" class="btn btn-default">Top travelers</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div id="map-canvas"></div>
    </div>

    {# Posts #}
    <div class="page-header text-center">
        <h2>Posts</h2>
    </div>
    <div class="row">
        <div class="col-6">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Most likes (per post)</span>
                </div>
                <div class="box-content">
                    <div class="box-col-2 box-blue">
                        <span class="large-text">{{ most_liked_male.average|floatformat:0 }}</span><br>
                        <span class="small-text">({{ most_liked_male.name|truncatechars:25 }})</span>
                    </div>
                    <div class="box-col-2 box-pink">
                        <span class="large-text">{{ most_liked_female.average|floatformat:0 }}</span><br>
                        <span class="small-text">({{ most_liked_female.name|truncatechars:25 }})</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="box">
                <div class="box-header">
                    <span class="large-text">Most posts</span>
                </div>
                <div class="box-content">
                    <div class="box-col-2 box-blue">
                        <span class="large-text">{{ most_active_male.total }}</span><br>
                        <span class="small-text">({{ most_active_male.name|truncatechars:25 }})</span>
                    </div>
                    <div class="box-col-2 box-pink">
                        <span class="large-text">{{ most_active_female.total }}</span><br>
                        <span class="small-text">({{ most_active_female.name|truncatechars:25 }})</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{# Javascript files #}
{% block js-foot %}
    {{ block.super }}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    {% load staticfiles %}
    <script src="{% static "js/report.js" %}"></script>
    <script src="{% static "js/highcharts.js" %}"></script>
{% endblock %}

fb/templates/status.html
{% extends "base.html" %}
{% block content %}

    {% load staticfiles %}
    <script src="{% static "js/progress.js" %}" ></script>

    <div class="row">
        <div class="col-lg-12">
            <h1>Report in progress (<span id="progress" data-id="{{ progress.id }}">{{ progress.percentage|floatformat:2 }}%</span>)</h1>
            <div class="progress">
                <div id="progress-bar" class="progress-bar" style="width: {{ progress.percentage|floatformat:2 }}%;"></div>
            </div>
            <p id="progress-description">test</p>
        </div>
    </div>

{% endblock %}